"""message

Revision ID: beee5bd55546
Revises: 368fb93097c9
Create Date: 2025-07-08 22:56:51.406263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'beee5bd55546'
down_revision = '368fb93097c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('kudago_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('publication_date', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('title', sa.String(), nullable=True))
    op.add_column('events', sa.Column('short_title', sa.String(), nullable=True))
    op.add_column('events', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('events', sa.Column('place', sa.String(), nullable=True))
    op.add_column('events', sa.Column('description', sa.String(), nullable=True))
    op.add_column('events', sa.Column('body_text', sa.String(), nullable=True))
    op.add_column('events', sa.Column('location', sa.String(), nullable=True))
    op.add_column('events', sa.Column('categories', sa.String(), nullable=True))
    op.add_column('events', sa.Column('tagline', sa.String(), nullable=True))
    op.add_column('events', sa.Column('age_restriction', sa.String(), nullable=True))
    op.add_column('events', sa.Column('price', sa.String(), nullable=True))
    op.add_column('events', sa.Column('is_free', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('images', sa.String(), nullable=True))
    op.add_column('events', sa.Column('favorites_count', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('comments_count', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('site_url', sa.String(), nullable=True))
    op.add_column('events', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('events', sa.Column('participants', sa.String(), nullable=True))
    op.alter_column('events', 'starts_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # --- ВАЖНО ---
    # Если старые строки не нужны, раскомментируйте следующую строку для очистки таблицы:
    # op.execute("TRUNCATE TABLE events;")
    # Если строки нужны, заполните kudago_id вручную через SQL UPDATE перед следующим шагом.
    # Очистить таблицу перед установкой NOT NULL:
    op.execute("TRUNCATE TABLE events;")
    op.alter_column('events', 'kudago_id', nullable=False)
    op.create_index(op.f('ix_events_kudago_id'), 'events', ['kudago_id'], unique=True)
    op.create_unique_constraint('uix_kudago_id', 'events', ['kudago_id'])
    op.drop_column('events', 'photo')
    op.drop_column('events', 'address')
    op.drop_column('events', 'join_link')
    op.drop_column('events', 'join_type')
    op.drop_column('events', 'name')
    op.drop_column('events', 'creator_id')
    op.drop_column('events', 'interests')
    op.alter_column('events', 'title', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('interests', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('join_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('join_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uix_kudago_id', 'events', type_='unique')
    op.drop_index(op.f('ix_events_kudago_id'), table_name='events')
    op.alter_column('events', 'starts_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('events', 'participants')
    op.drop_column('events', 'tags')
    op.drop_column('events', 'site_url')
    op.drop_column('events', 'comments_count')
    op.drop_column('events', 'favorites_count')
    op.drop_column('events', 'images')
    op.drop_column('events', 'is_free')
    op.drop_column('events', 'price')
    op.drop_column('events', 'age_restriction')
    op.drop_column('events', 'tagline')
    op.drop_column('events', 'categories')
    op.drop_column('events', 'location')
    op.drop_column('events', 'body_text')
    op.drop_column('events', 'description')
    op.drop_column('events', 'place')
    op.drop_column('events', 'slug')
    op.drop_column('events', 'short_title')
    op.drop_column('events', 'title')
    op.drop_column('events', 'publication_date')
    op.drop_column('events', 'kudago_id')
    # ### end Alembic commands ###
