"""update_event_structure_and_add_kudago_events_table

Revision ID: da76e3df044b
Revises: beee5bd55546
Create Date: 2025-07-10 23:38:37.312442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da76e3df044b'
down_revision = 'beee5bd55546'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kudago_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kudago_id', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kudago_id', name='uix_kudago_event_id')
    )
    op.execute("TRUNCATE TABLE events;")
    op.create_index(op.f('ix_kudago_events_kudago_id'), 'kudago_events', ['kudago_id'], unique=True)
    op.add_column('events', sa.Column('name', sa.String(), nullable=False))
    op.add_column('events', sa.Column('interests', sa.String(), nullable=False))
    op.add_column('events', sa.Column('address', sa.String(), nullable=False))
    op.add_column('events', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.add_column('events', sa.Column('join_type', sa.String(), nullable=True))
    op.add_column('events', sa.Column('join_link', sa.String(), nullable=True))
    op.add_column('events', sa.Column('photo', sa.String(), nullable=True))
    op.alter_column('events', 'starts_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_events_kudago_id'), table_name='events')
    op.drop_constraint(op.f('uix_kudago_id'), 'events', type_='unique')
    op.drop_column('events', 'body_text')
    op.drop_column('events', 'age_restriction')
    op.drop_column('events', 'place')
    op.drop_column('events', 'price')
    op.drop_column('events', 'publication_date')
    op.drop_column('events', 'location')
    op.drop_column('events', 'short_title')
    op.drop_column('events', 'favorites_count')
    op.drop_column('events', 'slug')
    op.drop_column('events', 'comments_count')
    op.drop_column('events', 'site_url')
    op.drop_column('events', 'description')
    op.drop_column('events', 'tags')
    op.drop_column('events', 'images')
    op.drop_column('events', 'kudago_id')
    op.drop_column('events', 'is_free')
    op.drop_column('events', 'title')
    op.drop_column('events', 'categories')
    op.drop_column('events', 'tagline')
    op.drop_column('events', 'participants')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('participants', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('tagline', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('categories', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('is_free', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('kudago_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('images', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('site_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('comments_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('favorites_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('short_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('publication_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('place', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('age_restriction', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('body_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uix_kudago_id'), 'events', ['kudago_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_events_kudago_id'), 'events', ['kudago_id'], unique=True)
    op.alter_column('events', 'starts_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('events', 'photo')
    op.drop_column('events', 'join_link')
    op.drop_column('events', 'join_type')
    op.drop_column('events', 'creator_id')
    op.drop_column('events', 'address')
    op.drop_column('events', 'interests')
    op.drop_column('events', 'name')
    op.drop_index(op.f('ix_kudago_events_kudago_id'), table_name='kudago_events')
    op.drop_table('kudago_events')
    # ### end Alembic commands ###
